version: '3.8'
services:
  
  #APP Service
  app:
    build:
      args:
        user: levon
        uid: 1000
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: app_vue
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    networks:
      - app-network

  #Nginx Service
  webserver:
    build: ./docker/nginx
    container_name: webserver_vue
    restart: unless-stopped
    tty: true
    ports:
     - '8001:80'
     - '44301:443'
    volumes:
      - ./:/var/www
      - ./docker/nginx-logs:/var/log/nginx
    networks:
      - app-network

 #MySQL Service
  db:
    image: mysql:8.0
    container_name: db_vue
    restart: always
    tty: true
    ports:
      - "3301:3306"
    environment:
      MYSQL_ROOT_HOSTS: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

  #Phpmyadmin
  phpmyadmin:
        depends_on:
          - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_vue
        restart: always
        ports:
          - 1080:80
        environment:
          PMA_HOST: db
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
           - app-network



#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
